# Generated by Django 3.0.8 on 2020-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='images/earth.jpg', upload_to='images/'),
        ),
    ]
