# Generated by Django 3.0.8 on 2020-08-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20200804_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Topping'),
        ),
    ]
